tags:
- name: Car Reservation
  description: Car Reservation API

paths:
# [GET] cars
  /cars:
    get:
      tags:
      - cars
      summary: Find All Cars
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] users
    post:
      tags:
      - cars
      summary: Add Car
      parameters:
      - name: body
        in: body
        description: car Data
        required: true
        schema:
          $ref: '#/definitions/cars'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] cars/id
  /cars/{id}:
    get:
      tags:
      - cars
      summary: Find Car By Id
      parameters:
      - name: id
        in: path
        description: Car Id
        required: true
        type: string
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] cars/id
    put:
      tags:
      - cars
      summary: Update Car By Id
      parameters:
      - name: id
        in: path
        description: car Id
        required: true
        type: string
      - name: body
        in: body
        description: car Data
        required: true
        schema:
          $ref: '#/definitions/cars'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] cars/id
    delete:
      tags:
      - cars
      summary: Delete Car By Id
      parameters:
      - name: id
        in: path
        description: cars Id
        required: true
        type: string
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /reservations:
    get:
      tags:
      - reservations
      summary: Find All Future Reservations
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] reservations
    post:
      tags:
      - reservations
      summary: Make a Reservation
      parameters:
      - name: body
        in: body
        description: reservation Data
        required: true
        schema:
          $ref: '#/definitions/reservations'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'


# definitions
definitions:
  cars:
    type: object
    required:
        - make
    properties:
      id:
        type: string
        pattern: '^C\d{9}$'
        description: car id (C<number>)
      make:
        type: string
        description: car make
        enum: [AlfaRomeo, Audi, BMW, Bentley, Cadillac, Chevrolet, Other]
  reservations:
    type: object
    required:
        - make
    properties:
      carId:
        type: string
        pattern: '^C\d{9}$'
        description: car id (C<number>)
      dateFrom:
        type: string
        format: date-time
      dateTo:
        type: string
        format: date-time

schemes:
 - https
 - http
